// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrnv7o-ddu1jTYKBhSdq1Aa8C3OUPXfl8',
    appId: '1:27270319087:web:b398260bb65d468c21841a',
    messagingSenderId: '27270319087',
    projectId: 'socialppbase',
    authDomain: 'socialppbase.firebaseapp.com',
    storageBucket: 'socialppbase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4g923ag-7znratZvNmbNK-NzEZJUl-EE',
    appId: '1:27270319087:android:10afef6933e364fe21841a',
    messagingSenderId: '27270319087',
    projectId: 'socialppbase',
    storageBucket: 'socialppbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSjFPfgdYHFHJjmJrNMaIsRo-YloCskAI',
    appId: '1:27270319087:ios:f9db92eee36d694b21841a',
    messagingSenderId: '27270319087',
    projectId: 'socialppbase',
    storageBucket: 'socialppbase.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaAppp',
  );
}
